MODEL:  
  TEMPERATURE: 0.2
  STREAM: True

  SERVICE: # [ ollama, openai, groq, gemini ] 

  EMBEDDING_MODEL_NAME: mixedbread-ai/mxbai-embed-large-v1
  EMBEDDING_SERVICE: hf # [ollama, openai, hf]

  MODEL_ID: 


  VECTOR_STORE: "chroma" # currently support [qdrant, chroma]
  PAPER_COLLECTION_NAME: "gemma_assistant_arxiv_papers"